import { Router } from "express";
import { forgotPassword, login, me, register, resetPassword } from "../controllers/authController.js";
import { protect } from "../middleware/auth.js";
const router = Router();
router.post("/register", register);
router.post("/login", login);
router.get("/me", protect, me);
router.post("/forgot-password", forgotPassword);
router.post("/reset-password", protect, resetPassword);
export default router;
